language: java

jdk:
- openjdk8

script:
  - |
    if [[ $TRAVIS_TAG =~ ^v.* ]]; then
      ./gradlew clean build publish -Prelease.useLastTag=true -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE}
    else
      ./gradlew clean build snapshot $(if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo "publish -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE}"; fi)
    fi

before_install:
  - openssl aes-256-cbc -K $encrypted_ef005e54dfe3_key -iv $encrypted_ef005e54dfe3_iv -in secret-key.gpg.enc -out secret-key.gpg -d

after_success:
  - bash <(curl -s https://codecov.io/bash)
